# Prometheus 설정
global:
  scrape_interval: 5s  # 5초마다 메트릭 수집
  evaluation_interval: 5s

scrape_configs:
  # Spring Boot Actuator 메트릭
  - job_name: 'pre-view'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']  # 로컬 Spring Boot
    scrape_interval: 5s
